name: peercoin
description: A new Peercoin wallet.

version: 0.9.3+90

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  web_socket_channel: ^2.1.0
  crypto: ^3.0.1
  bip39: ^1.0.6
  coinslib: ^3.1.3
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.6
  provider: ^6.0.3
  share_plus: ^4.0.3
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  step_progress_indicator: ^1.0.0
  qr_code_scanner: ^1.0.0
  url_launcher: ^6.1.2
  flutter_local_notifications: ^9.2.0
  flutter_screen_lock: ^4.0.4+1
  local_auth: ^1.1.10
  package_info_plus: ^1.4.0
  mailto: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_typeahead: ^4.0.0
  connectivity_plus: ^2.2.1
  theme_mode_handler: ^3.0.0
  http: ^0.13.3
  collection: ^1.15.0-nullsafety.4
  flutter_markdown: ^0.6.6
  background_fetch: ^1.0.1
  flutter_logs: ^2.1.6
  auto_size_text: ^3.0.0
  camera: ^0.9.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.4
  flutter_lints: ^1.0.4
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ppc-icon.png"
  image_path_ios: "assets/icon/ppc-ios-app-xxl.png"
  remove_alpha_ios: true

flutter_launcher_name:
  name: "Peercoin"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/ppc-icon-256.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/translations/
    - assets/img/
    - CHANGELOG.md
