name: peercoin
description: A new Peercoin wallet.

version: 0.6.4+59

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  web_socket_channel: ^2.1.0
  crypto: ^3.0.1
  bip39: ^1.0.6
  bitcoin_flutter:
    git:
      url: https://github.com/Vesta-wallet/bitcoin_flutter.git
      ref: null_safety_v1 #TODO v0.11 main net release: change to master
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hive_generator: ^1.1.0
  flutter_secure_storage: ^4.2.0
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  share: ^2.0.4
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  step_progress_indicator: ^1.0.0
  qr_code_scanner: ^0.5.1
  url_launcher: ^6.0.4
  flutter_local_notifications: ^6.0.0
  flutter_screen_lock: ^4.0.4+1
  local_auth: ^1.1.6
  package_info: ^2.0.2
  mailto: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_typeahead: ^3.1.3
  connectivity: ^3.0.6
  pedantic: ^1.11.0
  theme_mode_handler: ^3.0.0
  http: ^0.13.3
  cupertino_icons: ^1.0.3
  collection: ^1.15.0-nullsafety.4
  flutter_markdown: ^0.6.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.4
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ppc-icon.png"
  image_path_ios: "assets/icon/ppc-ios-app-xxl.png"
  remove_alpha_ios: true

flutter_launcher_name:
  name: "Peercoin"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/ppc-icon-256.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/translations/
    - assets/img/
    - CHANGELOG.md