name: peercoin
description: A new Peercoin wallet.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.9+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  web_socket_channel: ^1.2.0
  crypto: ^2.0.3
  bip39: ^1.0.3
  bitcoin_flutter:
    path: ../bitcoin_flutter
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  hive_generator: ^0.8.2
  flutter_secure_storage: ^4.1.0
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  share: ^0.6.5+4
  qr_flutter: ^3.2.0
  intl: ^0.17.0
  step_progress_indicator: ^0.2.5+8
  qr_code_scanner: ^0.4.0
  url_launcher: ^6.0.2
  flutter_local_notifications: ^5.0.0
  flutter_screen_lock: ^4.0.3
  local_auth: ^1.1.5
  package_info: ^2.0.0
  mailto: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: ^0.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ppc-icon.png"
  image_path_ios: "assets/icon/ppc-icon-white-bg.png"

  flutter_launcher_name:
  name: "Peercoin"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/ppc-icon-256.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/ppc-icon-256.png
    - assets/icon/ppc-icon-48.png
    - assets/icon/ppc-icon-white-256.png
    - assets/icon/ppc-icon-white-48.png
    - assets/translations/en.json
    - assets/translations/nl.json
    - assets/translations/de.json
    - assets/translations/ru.json
    - assets/translations/ro.json
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
