name: peercoin
description: A new Peercoin wallet.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.9+52

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  web_socket_channel: ^2.1.0
  crypto: ^3.0.1
  bip39: ^1.0.6
  bitcoin_flutter:
    git:
      url: https://github.com/Vesta-wallet/bitcoin_flutter.git
      ref: null_safety
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hive_generator: ^1.1.0
  flutter_secure_storage: ^4.2.0
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  share: ^2.0.4
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  step_progress_indicator: ^1.0.0
  qr_code_scanner: ^0.5.1
  url_launcher: ^6.0.4
  flutter_local_notifications: ^6.0.0
  flutter_screen_lock: ^4.0.4+1
  local_auth: ^1.1.6
  package_info: ^2.0.2
  mailto: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_typeahead: ^3.1.3
  connectivity: ^3.0.6
  pedantic: ^1.11.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ppc-icon.png"
  image_path_ios: "assets/icon/ppc-ios-app-xxl.png"
  remove_alpha_ios: true

  flutter_launcher_name:
  name: "Peercoin"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/ppc-icon-256.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/ppc-icon-256.png
    - assets/icon/ppc-icon-48.png
    - assets/icon/ppc-icon-white-256.png
    - assets/icon/ppc-icon-white-48.png
    - assets/icon/ppc-logo.png
    - assets/icon/ppc-ios-app-xxl.png
    - assets/translations/en.json
    - assets/translations/nl.json
    - assets/translations/de.json
    - assets/translations/ru.json
    - assets/translations/ro.json
    - assets/translations/zh.json
    - assets/translations/it.json
    - assets/translations/hr.json
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
